import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { AiOutlineHeart, AiFillHeart } from 'react-icons/ai';
import { useState } from 'react'
import pizza from '../public/pizza0.jpg'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [isLoved, setIsLoved] = useState<boolean>(false)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <header>
          <nav className={styles.nav}>
            <h1>Offers</h1>
            <ul className={styles.pages}>
              <li><Link href='/'>Home</Link></li>
              <li><Link href='/how-it-works'>How it works</Link></li>
              <li><Link href='/contact-us'>Contact Us</Link></li>
              <li><button>Log In</button></li>
            </ul>
          </nav>
        </header> */}
      <main className={styles.main}>
        <div>
          <section className={styles.section}>
            <Image src={pizza} alt="pizza" width={500} height={500} className={styles.photo}/>
            <button onClick={ () => setIsLoved(!isLoved)} className={isLoved? `${styles.heartClicked}`: `${styles.heart}` }> { isLoved? <AiFillHeart className={styles.iconStyles} /> : <AiOutlineHeart className={styles.iconStyles} />} Love</button> 
          </section>
        </div>
      </main>
    </>
  )
}
